name: Atlas Schema Diff and Migrate

on:
  workflow_dispatch:

jobs:
  atlas-migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Atlas CLI (manual method)
        run: |
          curl -Lo atlas.tar.gz https://github.com/ariga/atlas/releases/latest/download/atlas-linux-amd64.tar.gz
          mkdir -p ./atlas-bin
          tar -xzf atlas.tar.gz -C ./atlas-bin
          sudo mv ./atlas-bin/atlas /usr/local/bin

      - name: Setup migration directory
        run: mkdir -p atlas/migrations

      - name: Generate migration
        run: |
          atlas migrate diff \
            --dir atlas/migrations \
            --from "${{ secrets.URLDEV }}" \
            --to "${{ secrets.URLSTG }}" \
            --dev-url "docker://postgres/15" \
            --name "auto_diff"

      - name: Apply migration to staging
        run: |
          atlas migrate apply \
            --dir atlas/migrations \
            --url "${{ secrets.URLSTG }}"

      - name: Upload migration directory
        uses: actions/upload-artifact@v4
        with:
          name: atlas-migrations
          path: atlas/migrations
