name: Liquibase Aurora Schema Diff

on:
  workflow_dispatch:

jobs:
  liquibase-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download and Extract Liquibase
        run: |
          wget https://github.com/liquibase/liquibase/releases/download/v4.23.0/liquibase-4.23.0.tar.gz
          mkdir liquibase
          tar -xzf liquibase-4.23.0.tar.gz -C liquibase --strip-components=1

      - name: Download PostgreSQL JDBC Driver
        run: |
          wget https://jdbc.postgresql.org/download/postgresql-42.7.3.jar

      - name: Run Liquibase Diff between Dev and Prod
        run: |
          ./liquibase/liquibase \
            --classpath=postgresql-42.7.3.jar \
            --referenceUrl=jdbc:postgresql://${{ secrets.DEV_DB_HOST }}:5432/auroradev \
            --url=jdbc:postgresql://${{ secrets.PROD_DB_HOST }}:5432/auroradev \
            --username=${{ secrets.DB_USER }} \
            --password=${{ secrets.DB_PASSWORD }} \
            --changeLogFile=changelog/diff.xml \
            diffChangeLog
