name: Liquibase Diff

on:
  workflow_dispatch:

jobs:
  liquibase-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Liquibase
        run: |
          wget https://github.com/liquibase/liquibase/releases/download/v4.23.0/liquibase-4.23.0.tar.gz
          tar -xf liquibase-4.23.0.tar.gz
          sudo mv liquibase /usr/local/bin/

      - name: Download PostgreSQL JDBC Driver
        run: |
          wget https://jdbc.postgresql.org/download/postgresql-42.7.3.jar

      - name: Run Liquibase Diff
        run: |
          liquibase \
            --classpath=postgresql-42.7.3.jar \
            --referenceUrl=jdbc:postgresql://${{ secrets.DEV_DB_HOST }}/auroradev \
            --url=jdbc:postgresql://${{ secrets.PROD_DB_HOST }}/auroradev \
            --username=${{ secrets.DB_USER }} \
            --password=${{ secrets.DB_PASSWORD }} \
            --changeLogFile=changelog/diff.xml \
            diffChangeLog
