name: Atlas Schema Diff and Migrate

on:
  workflow_dispatch:

jobs:
  atlas-migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Atlas CLI
        run: |
          curl -sSf https://install.atlasgo.io | sh
          sudo mv ./bin/atlas /usr/local/bin

      - name: Setup migration directory
        run: mkdir -p atlas/migrations

      - name: Generate migration
        run: |
          atlas migrate diff \
            --dir atlas/migrations \
            --from "${{ secrets.URLDEV }}" \
            --to "${{ secrets.URLSTG }}" \
            --dev-url "docker://postgres/15" \
            --name "auto_diff"

      - name: Show generated migration files
        run: ls -l atlas/migrations

      - name: Apply migration to staging
        run: |
          atlas migrate apply \
            --dir atlas/migrations \
            --url "${{ secrets.URLSTG }}"

      - name: Upload migration directory
        uses: actions/upload-artifact@v4
        with:
          name: atlas-migrations
          path: atlas/migrations
