name: Atlas PostgreSQL Schema Diff

on:
  workflow_dispatch:

jobs:
  atlas-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Atlas CLI (latest method)
        run: |
          curl -s https://atlasgo.sh | bash
          echo "$HOME/.atlas/bin" >> $GITHUB_PATH

      - name: Verify Atlas CLI
        run: |
          atlas version

      - name: Run Atlas schema diff
        run: |
          atlas schema diff \
            --from "${{ secrets.URLDEV }}" \
            --to "${{ secrets.URLSTG }}" \
            --format atlas > db/migration.sql

      - name: Show migration SQL
        run: cat db/migration.sql

      - name: Apply migration to staging
        run: |
          atlas schema apply \
            --from file://db/migration.sql \
            --to "${{ secrets.URLSTG }}" \
            --auto-approve

      - name: Upload migration.sql as artifact
        uses: actions/upload-artifact@v4
        with:
          name: atlas-migration
          path: db/migration.sql
