name: Liquibase Aurora Schema Diff

on:
  workflow_dispatch:

jobs:
  liquibase-diff:
    runs-on: ubuntu-latest

    env:
      LIQUIBASE_VERSION: 4.23.0

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download and extract Liquibase
        run: |
          curl -L https://github.com/liquibase/liquibase/releases/download/v4.23.0/liquibase-4.23.0.zip -o liquibase.zip
          unzip liquibase.zip -d liquibase
          chmod +x liquibase/liquibase

      - name: Download PostgreSQL JDBC driver
        run: |
          curl -L -o liquibase/postgresql.jar https://jdbc.postgresql.org/download/postgresql-42.7.3.jar

      - name: Run Liquibase Diff and Show Output
        run: |
          ./liquibase/liquibase \
            --classpath=liquibase/postgresql.jar \
            --url="jdbc:postgresql://auroradev-instance-1.clqsa8muy6bd.us-east-2.rds.amazonaws.com:5432/auroradev" \
            --username=postgres \
            --password='*Gatsby1975' \
            --referenceUrl="jdbc:postgresql://auroradev-instance-1.clqsa8muy6bd.us-east-2.rds.amazonaws.com:5432/aurorastg" \
            --referenceUsername=postgres \
            --referencePassword='*Gatsby1975' \
            --changelog-file=db/changelog/db.changelog-master.xml \
            diffChangeLog

          # Fix invalid XML declaration for Liquibase compatibility
          sed -i '1s/^\xEF\xBB\xBF<?xml version="1.1"/<?xml version="1.0"/' db/changelog/db.changelog-master.xml
          sed -i '1s/^[[:space:]]*<?xml version="1.1"/<?xml version="1.0"/' db/changelog/db.changelog-master.xml

          echo "==== CHANGELOG DIFF ===="
          cat db/changelog/db.changelog-master.xml

      - name: Apply Changelog to Target (auroradev)
        run: |
          ./liquibase/liquibase \
            --classpath=liquibase/postgresql.jar \
            --url="jdbc:postgresql://auroradev-instance-1.clqsa8muy6bd.us-east-2.rds.amazonaws.com:5432/auroradev" \
            --username=postgres \
            --password=*Gatsby1975 \
            --changeLogFile=db/changelog/db.changelog-master.xml \
            update

      - name: Upload changelog artifact
        uses: actions/upload-artifact@v4
        with:
          name: diff-changelog
          path: db/changelog/db.changelog-master.xml
