name: Atlas PostgreSQL Schema Diff

on:
  workflow_dispatch:

jobs:
  atlas-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Atlas CLI
        run: |
          curl -sSf https://atlasgo.io/install.sh | sh
          echo "$HOME/.atlas/bin" >> $GITHUB_PATH

      - name: Create atlas.hcl config
        run: |
          mkdir -p db
          cat <<EOF > db/atlas.hcl
          env "default" {
            dev = "${{ secrets.URLDEV }}"
            url = "${{ secrets.URLSTG }}"
          }
          EOF

      - name: Run Atlas schema diff
        run: |
          atlas schema diff \
            --dev-url "${{ secrets.URLDEV }}" \
            --to "${{ secrets.URLSTG }}" \
            --format atlas > db/migration.sql

      - name: Output schema diff
        run: |
          echo "==== Schema Diff ===="
          cat db/migration.sql

      - name: Upload diff artifact
        uses: actions/upload-artifact@v4
        with:
          name: atlas-schema-diff
          path: db/migration.sql
