name: Atlas PostgreSQL Schema Diff

on:
  workflow_dispatch:

jobs:
  atlas-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Atlas CLI (latest method)
        run: |
          curl -s https://atlasgo.sh | bash
          echo "$HOME/.atlas/bin" >> $GITHUB_PATH
      - name: Verify Atlas CLI
        run: |
          atlas version
          
      - name: Run Atlas schema diff
        run: |
          atlas schema diff \
            --from "${{ secrets.URLDEV }}" \
            --to "${{ secrets.URLSTG }}" \
            --dev-url "docker://postgres/15" \
            --format sql > db/migration.sql
  
      - name: Show migration SQL
        run: cat db/migration.sql
      
      - name: Apply migration SQL using psql
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          PGPASSWORD='${{ secrets.DB_PASSWORD }}' psql \
            -h auroradev-instance-1.clqsa8muy6bd.us-east-2.rds.amazonaws.com,5432 \
            -U postgres \
            -d aurorastg \
            -f db/migration.sql


      - name: Upload diff artifact
        uses: actions/upload-artifact@v4
        with:
          name: atlas-schema-diff
          path: db/migration.sql
