name: Atlas PostgreSQL Schema Sync

on:
  workflow_dispatch:

jobs:
  atlas-diff-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Atlas CLI (v0.36.0)
        run: |
          curl -sSf https://release.ariga.io/atlas/atlas-community-linux-amd64-v0.36.0 -o atlas
          chmod +x atlas
          sudo mv atlas /usr/local/bin/atlas


      - name: Run Atlas Schema Diff and show output
        run: |
          atlas schema diff \
            --from "${{ secrets.URLSTG }}" \
            --to "${{ secrets.URLDEV }}" \
            --dev-url "docker://postgres/15" \
            --log sql

      - name: Apply Schema Changes to DEV
        run: |
          atlas schema apply \
            --to "${{ secrets.URLDEV }}" \
            --from "${{ secrets.URLSTG }}" \
            --dev-url "docker://postgres/15" \
            --auto-approve
