name: Liquibase Diff

on:
  workflow_dispatch:

jobs:
  diff-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Liquibase
        run: |
          curl -s https://download.liquibase.com/liquibase-4.23.0.tar.gz | tar xz
          sudo mv liquibase /usr/local/bin

      - name: Run Liquibase Diff
        run: |
          liquibase \
            --classpath=postgresql-42.7.3.jar \
            --referenceUrl=jdbc:postgresql://${{ secrets.DEV_DB_HOST }}/auroradev \
            --url=jdbc:postgresql://${{ secrets.PROD_DB_HOST }}/auroradev \
            --username=${{ secrets.DB_USER }} \
            --password=${{ secrets.DB_PASSWORD }} \
            --changeLogFile=diff.xml \
            diffChangeLog
