name: Atlas PostgreSQL Schema Diff and Apply

on:
  workflow_dispatch:

jobs:
  atlas-migration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Atlas CLI
        run: |
          curl -s https://atlasgo.sh | bash
          echo "$HOME/.atlas/bin" >> $GITHUB_PATH

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Verify Atlas CLI
        run: atlas version

      - name: Generate migration SQL (DEV → STG)
        run: |
          atlas schema diff \
            --dev-url "docker://postgres/15" \
            --from "${{ secrets.URLDEV }}" \
            --to "${{ secrets.URLSTG }}" \
            > db/migration.sql

      - name: Show generated SQL
        run: cat db/migration.sql

      - name: Apply SQL to Staging DB
        run: |
          psql "${{ secrets.URLSTG }}" -f db/migration.sql

      - name: Upload SQL artifact
        uses: actions/upload-artifact@v4
        with:
          name: atlas-schema-diff
          path: db/migration.sql
