name: Liquibase Aurora Schema Diff

on:
  workflow_dispatch:

jobs:
  liquibase-diff:
    runs-on: ubuntu-latest

    env:
      LIQUIBASE_VERSION: 4.23.0

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Liquibase
        run: |
          curl -L https://github.com/liquibase/liquibase/releases/download/v${LIQUIBASE_VERSION}/liquibase-${LIQUIBASE_VERSION}.tar.gz -o liquibase.tar.gz
          mkdir liquibase
          tar -xzf liquibase.tar.gz -C liquibase --strip-components=1
          chmod +x liquibase/liquibase

      - name: Download PostgreSQL JDBC driver
        run: |
          curl -L -o liquibase/postgresql.jar https://jdbc.postgresql.org/download/postgresql-42.7.3.jar

      - name: Run Liquibase Diff
        run: |
          ./liquibase/liquibase \
            --classpath=liquibase/postgresql.jar \
            --referenceUrl=jdbc:postgresql://${{ secrets.DEV_DB_HOST }} \
            --url=jdbc:postgresql://${{ secrets.PROD_DB_HOST }} \
            --username=${{ secrets.DB_USER }} \
            --password=${{ secrets.DB_PASSWORD }} \
            diffChangeLog \
            --changelog-file=changelog/diff.xml

      - name: Upload changelog artifact
        uses: actions/upload-artifact@v4
        with:
          name: diff-changelog
          path: changelog/diff.xml
