name: Atlas PostgreSQL Schema Sync

on:
  workflow_dispatch:

jobs:
  atlas-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Atlas CLI (v0.35.0)
        run: |
          curl -Lo atlas https://release.ariga.io/atlas/atlas-community-linux-amd64-v0.35.0
          chmod +x atlas
          sudo mv atlas /usr/local/bin/atlas

      - name: Setup migration directory
        run: mkdir -p atlas/migrations

      - name: Generate and preview diff (STG → DEV)
        run: |
          atlas migrate diff \
            --dir atlas/migrations \
            --from "${{ secrets.URLSTG }}" \
            --to "${{ secrets.URLDEV }}"
          echo "=== Generated SQL Diff: ==="
          ls atlas/migrations/*.sql
          cat atlas/migrations/*.sql

      - name: Apply changes to DEV
        run: |
          atlas migrate apply \
            --dir atlas/migrations \
            --url "${{ secrets.URLDEV }}"

      - name: Upload migration files
        uses: actions/upload-artifact@v4
        with:
          name: atlas-migrations
          path: atlas/migrations
