name: Apply Pre-Generated Schema SQL to Target DB

on:
  push:
    paths:
      - db/compare.sql
  workflow_dispatch:

jobs:
  apply-schema:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Show SQL for verification
        run: cat db/compare.sql

      - name: Apply SQL to Target DB (Staging)
        run: |
          psql "${{ secrets.URLSTG }}" -f db/compare.sql
